# Financement du projet RackPredictor

# GitHub Sponsors (remplacer par votre username si vous configurez GitHub Sponsors)
# github: [votre-username]

# Pour les licences commerciales ou support prioritaire:
custom: ["https://github.com/votre-username/RackPredictor/issues/new?template=commercial-license.md"]
